[relaychain]
default_command = "./bin/polkadot"
chain = "kusama-local"

  [[relaychain.nodes]]
  name = "alice"
  ws_port = 9944
  validator = true

  [[relaychain.nodes]]
  name = "bob"
  ws_port = 9945
  validator = true

[[parachains]]
id = 1000
add_to_genesis = true
cumulus_based = true
chain = "statemine-local"

  [[parachains.collators]]
  name = "statemine-collator"
  command = "./bin/asset-hub"
  ws_port = 9946

[types.Header]
number = "u64"
weight = "u64"
parent_hash = "Hash"
post_state = "Hash"


