pub mod module_auction;
pub mod module_continuum;
pub mod module_currencies;
pub mod module_economy;
pub mod module_emergency;
pub mod module_estate;
pub mod module_metaverse;
pub mod module_mining;
pub mod module_nft;
