FROM rust:buster as builder
WORKDIR /app

RUN rustup default nightly-2022-05-11 && \
        rustup target add wasm32-unknown-unknown --toolchain nightly-2022-05-11

RUN apt-get update && \
        apt-get dist-upgrade -y -o Dpkg::Options::="--force-confold" && \
        apt-get install -y cmake pkg-config libssl-dev git clang libclang-dev

ARG GIT_COMMIT=
ENV GIT_COMMIT=$GIT_COMMIT
ARG BUILD_ARGS
ARG PROFILE=release

COPY . .

RUN cargo build --release --features=with-pioneer-runtime

# =============

FROM phusion/baseimage:focal-1.2.0
LABEL maintainer="justin@bit.country"

ARG PROFILE

RUN useradd -m -u 1000 -U -s /bin/sh -d /metaverse metaverse

COPY --from=builder /app/target/release/metaverse-node /usr/local/bin

# checks
RUN ldd /usr/local/bin/metaverse-node && \
        /usr/local/bin/metaverse-node --version

# Shrinking
RUN rm -rf /usr/lib/python* && \
        rm -rf /usr/sbin /usr/share/man

USER metaverse
EXPOSE 30333 9933 9944

RUN mkdir /metaverse/data

VOLUME ["/metaverse/data"]

ENTRYPOINT ["/usr/local/bin/metaverse-node"]