// This file is part of Metaverse.Network & Bit.Country.

// Copyright (C) 2020-2022 Metaverse.Network & Bit.Country .
// SPDX-License-Identifier: Apache-2.0

// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// 	http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//! Autogenerated weights for economy
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 4.0.0-dev
//! DATE: 2023-06-21, STEPS: `20`, REPEAT: 10, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! EXECUTION: Some(Wasm), WASM-EXECUTION: Compiled, CHAIN: None, DB CACHE: 1024

// Executed Command:
// ./target/release/metaverse-node
// benchmark
// pallet
// --execution=wasm
// --wasm-execution=compiled
// --pallet
// economy
// --extrinsic
// *
// --steps
// 20
// --repeat
// 10
// --template=./template/weight-template.hbs
// --output
// ./pallets/economy/src/weights.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use sp_std::marker::PhantomData;

/// Weight functions needed for economy.
pub trait WeightInfo {	fn set_bit_power_exchange_rate() -> Weight;	fn set_power_balance() -> Weight;	fn stake_a() -> Weight;	fn stake_b() -> Weight;	fn unstake_a() -> Weight;	fn unstake_b() -> Weight;	fn unstake_new_estate_owner() -> Weight;	fn withdraw_unreserved() -> Weight;}

/// Weights for economy using the for collator node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {	// Storage: Economy BitPowerExchangeRate (r:0 w:1)
	// Proof Skipped: Economy BitPowerExchangeRate (max_values: Some(1), max_size: None, mode: Measured)
	fn set_bit_power_exchange_rate() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `919`
		//  Estimated: `919`
		// Minimum execution time: 11_685 nanoseconds.
		Weight::from_parts(12_108_000, 919)
			.saturating_add(T::DbWeight::get().writes(1))
	}
	// Storage: Economy PowerBalance (r:0 w:1)
	// Proof Skipped: Economy PowerBalance (max_values: None, max_size: None, mode: Measured)
	fn set_power_balance() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `919`
		//  Estimated: `919`
		// Minimum execution time: 12_284 nanoseconds.
		Weight::from_parts(12_785_000, 919)
			.saturating_add(T::DbWeight::get().writes(1))
	}
	// Storage: Mining Round (r:1 w:0)
	// Proof Skipped: Mining Round (max_values: Some(1), max_size: None, mode: Measured)
	// Storage: Economy ExitQueue (r:1 w:0)
	// Proof Skipped: Economy ExitQueue (max_values: None, max_size: None, mode: Measured)
	// Storage: Economy StakingInfo (r:1 w:1)
	// Proof Skipped: Economy StakingInfo (max_values: None, max_size: None, mode: Measured)
	// Storage: Economy TotalStake (r:1 w:1)
	// Proof Skipped: Economy TotalStake (max_values: Some(1), max_size: None, mode: Measured)
	fn stake_a() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1496`
		//  Estimated: `11924`
		// Minimum execution time: 29_836 nanoseconds.
		Weight::from_parts(30_929_000, 11924)
			.saturating_add(T::DbWeight::get().reads(4))
			.saturating_add(T::DbWeight::get().writes(2))
	}
	// Storage: Mining Round (r:1 w:0)
	// Proof Skipped: Mining Round (max_values: Some(1), max_size: None, mode: Measured)
	// Storage: Economy EstateExitQueue (r:1 w:0)
	// Proof Skipped: Economy EstateExitQueue (max_values: None, max_size: None, mode: Measured)
	// Storage: Estate Estates (r:1 w:0)
	// Proof Skipped: Estate Estates (max_values: None, max_size: None, mode: Measured)
	// Storage: Estate EstateOwner (r:1 w:0)
	// Proof Skipped: Estate EstateOwner (max_values: None, max_size: None, mode: Measured)
	// Storage: OrmlNFT Tokens (r:1 w:0)
	// Proof Skipped: OrmlNFT Tokens (max_values: None, max_size: None, mode: Measured)
	// Storage: Economy EstateStakingInfo (r:1 w:1)
	// Proof Skipped: Economy EstateStakingInfo (max_values: None, max_size: None, mode: Measured)
	// Storage: Economy TotalEstateStake (r:1 w:1)
	// Proof Skipped: Economy TotalEstateStake (max_values: Some(1), max_size: None, mode: Measured)
	fn stake_b() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `2144`
		//  Estimated: `28373`
		// Minimum execution time: 45_093 nanoseconds.
		Weight::from_parts(48_615_000, 28373)
			.saturating_add(T::DbWeight::get().reads(7))
			.saturating_add(T::DbWeight::get().writes(2))
	}
	// Storage: Economy StakingInfo (r:1 w:1)
	// Proof Skipped: Economy StakingInfo (max_values: None, max_size: None, mode: Measured)
	// Storage: Mining Round (r:1 w:0)
	// Proof Skipped: Mining Round (max_values: Some(1), max_size: None, mode: Measured)
	// Storage: Economy ExitQueue (r:1 w:1)
	// Proof Skipped: Economy ExitQueue (max_values: None, max_size: None, mode: Measured)
	// Storage: Economy TotalStake (r:1 w:1)
	// Proof Skipped: Economy TotalStake (max_values: Some(1), max_size: None, mode: Measured)
	fn unstake_a() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1233`
		//  Estimated: `10872`
		// Minimum execution time: 22_126 nanoseconds.
		Weight::from_parts(23_896_000, 10872)
			.saturating_add(T::DbWeight::get().reads(4))
			.saturating_add(T::DbWeight::get().writes(3))
	}
	// Storage: Estate Estates (r:1 w:0)
	// Proof Skipped: Estate Estates (max_values: None, max_size: None, mode: Measured)
	// Storage: Economy EstateStakingInfo (r:1 w:1)
	// Proof Skipped: Economy EstateStakingInfo (max_values: None, max_size: None, mode: Measured)
	// Storage: Mining Round (r:1 w:0)
	// Proof Skipped: Mining Round (max_values: Some(1), max_size: None, mode: Measured)
	// Storage: Economy EstateExitQueue (r:1 w:1)
	// Proof Skipped: Economy EstateExitQueue (max_values: None, max_size: None, mode: Measured)
	// Storage: Economy TotalEstateStake (r:1 w:1)
	// Proof Skipped: Economy TotalEstateStake (max_values: Some(1), max_size: None, mode: Measured)
	fn unstake_b() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1489`
		//  Estimated: `15860`
		// Minimum execution time: 31_005 nanoseconds.
		Weight::from_parts(32_916_000, 15860)
			.saturating_add(T::DbWeight::get().reads(5))
			.saturating_add(T::DbWeight::get().writes(3))
	}
	// Storage: Estate Estates (r:1 w:0)
	// Proof Skipped: Estate Estates (max_values: None, max_size: None, mode: Measured)
	// Storage: Estate EstateOwner (r:1 w:0)
	// Proof Skipped: Estate EstateOwner (max_values: None, max_size: None, mode: Measured)
	// Storage: OrmlNFT Tokens (r:1 w:0)
	// Proof Skipped: OrmlNFT Tokens (max_values: None, max_size: None, mode: Measured)
	// Storage: Economy EstateStakingInfo (r:1 w:1)
	// Proof Skipped: Economy EstateStakingInfo (max_values: None, max_size: None, mode: Measured)
	// Storage: Mining Round (r:1 w:0)
	// Proof Skipped: Mining Round (max_values: Some(1), max_size: None, mode: Measured)
	// Storage: Economy TotalEstateStake (r:1 w:1)
	// Proof Skipped: Economy TotalEstateStake (max_values: Some(1), max_size: None, mode: Measured)
	// Storage: Economy EstateExitQueue (r:0 w:1)
	// Proof Skipped: Economy EstateExitQueue (max_values: None, max_size: None, mode: Measured)
	fn unstake_new_estate_owner() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1914`
		//  Estimated: `24288`
		// Minimum execution time: 36_727 nanoseconds.
		Weight::from_parts(38_216_000, 24288)
			.saturating_add(T::DbWeight::get().reads(6))
			.saturating_add(T::DbWeight::get().writes(3))
	}
	// Storage: Economy ExitQueue (r:1 w:1)
	// Proof Skipped: Economy ExitQueue (max_values: None, max_size: None, mode: Measured)
	fn withdraw_unreserved() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1568`
		//  Estimated: `4043`
		// Minimum execution time: 24_239 nanoseconds.
		Weight::from_parts(25_134_000, 4043)
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
}

// For backwards compatibility and tests
impl WeightInfo for () {	fn set_bit_power_exchange_rate() -> Weight {
		Weight::from_parts(12_108_000, 919)
			.saturating_add(RocksDbWeight::get().writes(1))
	}
	fn set_power_balance() -> Weight {
		Weight::from_parts(12_785_000, 919)
			.saturating_add(RocksDbWeight::get().writes(1))
	}
	fn stake_a() -> Weight {
		Weight::from_parts(30_929_000, 11924)
			.saturating_add(RocksDbWeight::get().reads(4))
			.saturating_add(RocksDbWeight::get().writes(2))
	}
	fn stake_b() -> Weight {
		Weight::from_parts(48_615_000, 28373)
			.saturating_add(RocksDbWeight::get().reads(7))
			.saturating_add(RocksDbWeight::get().writes(2))
	}
	fn unstake_a() -> Weight {
		Weight::from_parts(23_896_000, 10872)
			.saturating_add(RocksDbWeight::get().reads(4))
			.saturating_add(RocksDbWeight::get().writes(3))
	}
	fn unstake_b() -> Weight {
		Weight::from_parts(32_916_000, 15860)
			.saturating_add(RocksDbWeight::get().reads(5))
			.saturating_add(RocksDbWeight::get().writes(3))
	}
	fn unstake_new_estate_owner() -> Weight {
		Weight::from_parts(38_216_000, 24288)
			.saturating_add(RocksDbWeight::get().reads(6))
			.saturating_add(RocksDbWeight::get().writes(3))
	}
	fn withdraw_unreserved() -> Weight {
		Weight::from_parts(25_134_000, 4043)
			.saturating_add(RocksDbWeight::get().reads(1))
			.saturating_add(RocksDbWeight::get().writes(1))
	}
}
