// This file is part of Metaverse.Network & Bit.Country.

// Copyright (C) 2020-2022 Metaverse.Network & Bit.Country .
// SPDX-License-Identifier: Apache-2.0

// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// 	http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//! Autogenerated weights for economy
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 4.0.0-dev
//! DATE: 2023-02-10, STEPS: `20`, REPEAT: 10, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! EXECUTION: Some(Wasm), WASM-EXECUTION: Compiled, CHAIN: None, DB CACHE: 1024

// Executed Command:
// ./target/release/metaverse-node
// benchmark
// pallet
// --execution=wasm
// --wasm-execution=compiled
// --pallet
// economy
// --extrinsic
// *
// --steps
// 20
// --repeat
// 10
// --template=./template/weight-template.hbs
// --output
// ./pallets/economy/src/weights.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(clippy::unnecessary_cast)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use sp_std::marker::PhantomData;

/// Weight functions needed for economy.
pub trait WeightInfo {	fn set_bit_power_exchange_rate() -> Weight;	fn set_power_balance() -> Weight;	fn stake_a() -> Weight;	fn stake_b() -> Weight;	fn unstake_a() -> Weight;	fn unstake_b() -> Weight;	fn unstake_new_estate_owner() -> Weight;	fn withdraw_unreserved() -> Weight;}

/// Weights for economy using the for collator node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {	fn set_bit_power_exchange_rate() -> Weight {
	Weight::from_parts(36_400_000, 0)			.saturating_add(T::DbWeight::get().reads(1 as u64))			.saturating_add(T::DbWeight::get().writes(2 as u64))	}	fn set_power_balance() -> Weight {
	Weight::from_parts(40_400_000, 0)			.saturating_add(T::DbWeight::get().reads(1 as u64))			.saturating_add(T::DbWeight::get().writes(2 as u64))	}	fn stake_a() -> Weight {
	Weight::from_parts(85_100_000, 0)			.saturating_add(T::DbWeight::get().reads(5 as u64))			.saturating_add(T::DbWeight::get().writes(3 as u64))	}	fn stake_b() -> Weight {
	Weight::from_parts(109_700_000, 0)			.saturating_add(T::DbWeight::get().reads(8 as u64))			.saturating_add(T::DbWeight::get().writes(3 as u64))	}	fn unstake_a() -> Weight {
	Weight::from_parts(59_500_000, 0)			.saturating_add(T::DbWeight::get().reads(5 as u64))			.saturating_add(T::DbWeight::get().writes(4 as u64))	}	fn unstake_b() -> Weight {
	Weight::from_parts(62_200_000, 0)			.saturating_add(T::DbWeight::get().reads(5 as u64))			.saturating_add(T::DbWeight::get().writes(4 as u64))	}	fn unstake_new_estate_owner() -> Weight {
	Weight::from_parts(81_200_000, 0)			.saturating_add(T::DbWeight::get().reads(7 as u64))			.saturating_add(T::DbWeight::get().writes(4 as u64))	}	fn withdraw_unreserved() -> Weight {
	Weight::from_parts(76_400_000, 0)			.saturating_add(T::DbWeight::get().reads(2 as u64))			.saturating_add(T::DbWeight::get().writes(2 as u64))	}}

// For backwards compatibility and tests
impl WeightInfo for () {	fn set_bit_power_exchange_rate() -> Weight {
	Weight::from_parts(36_400_000, 0)			.saturating_add(RocksDbWeight::get().reads(1 as u64))			.saturating_add(RocksDbWeight::get().writes(2 as u64))	}	fn set_power_balance() -> Weight {
	Weight::from_parts(40_400_000, 0)			.saturating_add(RocksDbWeight::get().reads(1 as u64))			.saturating_add(RocksDbWeight::get().writes(2 as u64))	}	fn stake_a() -> Weight {
	Weight::from_parts(85_100_000, 0)			.saturating_add(RocksDbWeight::get().reads(5 as u64))			.saturating_add(RocksDbWeight::get().writes(3 as u64))	}	fn stake_b() -> Weight {
	Weight::from_parts(109_700_000, 0)			.saturating_add(RocksDbWeight::get().reads(8 as u64))			.saturating_add(RocksDbWeight::get().writes(3 as u64))	}	fn unstake_a() -> Weight {
	Weight::from_parts(59_500_000, 0)			.saturating_add(RocksDbWeight::get().reads(5 as u64))			.saturating_add(RocksDbWeight::get().writes(4 as u64))	}	fn unstake_b() -> Weight {
	Weight::from_parts(62_200_000, 0)				.saturating_add(RocksDbWeight::get().reads(5 as u64))			.saturating_add(RocksDbWeight::get().writes(4 as u64))	}	fn unstake_new_estate_owner() -> Weight {
	Weight::from_parts(81_200_000, 0)			.saturating_add(RocksDbWeight::get().reads(7 as u64))			.saturating_add(RocksDbWeight::get().writes(4 as u64))	}	fn withdraw_unreserved() -> Weight {
	Weight::from_parts(76_400_000, 0)			.saturating_add(RocksDbWeight::get().reads(2 as u64))			.saturating_add(RocksDbWeight::get().writes(2 as u64))	}}
